background: 0
B: 1
BnT: 2
CD4: 3
CD8: 4
DC: 5
Fibro: 6
HLADR: 7
Igg: 8
MDSC: 9
MacCD163: 10
MacCD204: 11
MacCD204_CD209: 12
MacCD209: 13
Mural: 14
NK: 15
Neutrophil: 16
PMN_MDSC: 17
SMA: 18
Treg: 19
Tumor: 20
Vasculature: 21
mregDC: 22
pDC: 23
plasma: 24
undefined: 25
vCAF: 26
