- Object: 
  - Cell:
    - Immune:
      - Lympho:
        - B:
          - B
          - plasma
          - Igg
        - T:
          - CD4
          - CD8
          - Treg
        - BnT
        - NK
        - pDC

      - Myeloid:
        - Dendritic:
          - DC
          - mregDC
        - Granulocytes:
          - Neutrophil
          - PMN-MDSC
          - MDSC
        - Macrophage:
          - MacCD204
          - MacCD204&209
          - MacCD209
          - MacCD163
      
      - HLADR

    - Stroma:
      - Fibroblast:
        - SMA 
        - Fibro 
        - vCAF
      - Mural

    - Vasculature 
    - Tumor 
    - undefined

  - background
